### ISSUE TITLE
Title of David Blei's Keynote

### ISSUE THREAD

**Issue by niekveldhuis** [TextXD/textxd-2022.github.io#18]
Do we have a title yet?

**Comment by iamciera** [comment]
Emailed David on November 17, 2022.

**Comment by iamciera** [comment]
Beyond Roll Call: Inferring Politics from Text

The ideal point model is a staple of quantitative political science. It is a probabilistic model of roll call data---how a group of lawmakers vote on a collection of bills---that can be used to quantify the lawmakers' political positions, which are called "ideal points." In this talk, I will discuss two ways to incorporate political texts into ideal point models. One source of text is the collection of bills. The issue-adjusted ideal point model helps capture how a lawmaker's political position might change depending on the content of the bill under consideration. It helps find sensible multi-dimensional ideal points, which are difficult to estimate from the votes alone. Another source of text comes from the lawmakers. In addition to voting, lawmakers express their political positions through speeches, press statements, and tweets. The text-based ideal point model can be used to analyze a collection of texts to quantify the political positions of their authors.  It helps find ideal points for anyone who authors political texts, including non-voting actors like candidates and political commentators.

**Comment by iamciera** [comment]
Added.
