### ISSUE TITLE
Notes from the weekly meeting relating to the website

### ISSUE THREAD

**Issue by ilyaakdemir** [TextXD/textxd-2022.github.io#19]
1) - [x] A clickable button to "program/schedule" near/under the “stay updated” or "buy your tickets" button that leads directly to the schedule
2) - [x] Remove “in partnership with CDSS” - they didn't do anything. 
3) Typos: 
- [x] Day 1: "5:30pmpm Opening Reception" - should be "5:30pm"
- [x] Day 2 and 3: "8:30am - 9:40am" - probably shouldn't include end time, given that other things in the program don't have end time?
- [x] Day 3: "9:30: - Welcome back" should be a newline

**Comment by iamciera** [comment]
Addressed all of them.
