### ISSUE TITLE
day 2 lightning talks

### ISSUE THREAD

**Issue by isaacdalke** [TextXD/textxd-2022.github.io#23]
Another tiny issue, but for the day 2 lightning talks can we put the subsession titles on a separate line from the first presentation? (So that the formatting matches the day 3 lightning talks)?

_Current:_

**Sub-Session: Scripting Culture, Smashing Politics Lightning 3.1**: Jaren Haber, Does Website Text Signal Quality & Fit for Schools of Choice?: Evidence from Online Experiments

**Sub-Session: The Hidden Structures of Science Lightning 3.4:** Xiangyi Meng, Hidden Citations Obscure True Impact in Science

_Suggested change:_

**Sub-Session: Scripting Culture, Smashing Politics** 
**Lightning 3.1:** Jaren Haber, Does Website Text Signal Quality & Fit for Schools of Choice?: Evidence from Online Experiments

**Sub-Session: The Hidden Structures of Science**
**Lightning 3.4:** Xiangyi Meng, Hidden Citations Obscure True Impact in Science

**Comment by iamciera** [comment]
Fixed
