### ISSUE TITLE
TextXD Cancellation 

### ISSUE THREAD

**Issue by maryamv** [TextXD/textxd-2022.github.io#24]
- Let's add the reason for our cancellation on the front page.

> 11/30/22 Update: TextXD has been cancelled (add a link) due to UAW (add a link) strike at the University of California. 

-  About page:  at the bottom, (1) Tim needs to be added to a new line and (2) Let's spell out BIDS. (3) remove our email addresses unless we want a lot spam emails :)

**Comment by iamciera** [comment]
fixed
