### ISSUE TITLE
Add clickable buttons on main page 

### ISSUE THREAD

**Issue by maryamv** [TextXD/textxd-2022.github.io#8]
Add two more clickable buttons next to "Stay Updated" for

1.  Submit your Abstract
2.  Buy your Tickets
3. Secure your spot in the trainings

**Comment by iamciera** [comment]
Are you doing this? Or do you want me to?

**Comment by iamciera** [comment]
Okay, I added two buttons in a branch called "[dev-buttons](https://github.com/TextXD/textxd-2022.github.io/tree/dev-buttons)". You just need to add links in the file: /Users/ciera_pro/websites/textxd-2022.github.io/themes/vixcon-hugo/layouts/index.html. See below

This is what it looks like
<img width="1030" alt="Screen Shot 2022-07-07 at 3 14 18 PM" src="https://user-images.githubusercontent.com/1732390/177880439-9781b1e1-8a97-487e-8acb-67e4ce682906.png">

This is where you added the links in the code:
<img width="626" alt="Screen Shot 2022-07-07 at 3 18 39 PM" src="https://user-images.githubusercontent.com/1732390/177880857-4171ebc9-3e91-42b4-9a10-2e31cfd9b073.png">

**Comment by maryamv** [comment]
Thanks, Ciera! I added the links and merged the branch.
